on: [push]

name: Build

env:
  GIT_AUTHOR_NAME: actions
  GIT_AUTHOR_EMAIL: wjessen@thefarmersdog.com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - uses: jetli/trunk-action@v0.4.0
      - uses: rustup target add wasm32-unknown-unknown
      - run: trunk build --release -d docs
      - uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_PAT }}
