on: [push]

name: Build

env:
  GIT_AUTHOR_NAME: actions
  GIT_AUTHOR_EMAIL: wjessen@thefarmersdog.com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - run: cargo build --release 
      - run: cp -a dist/* docs
      - run: git add docs/ 
      - uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_PAT }}
