on: [push]

name: Build

env:
  GIT_AUTHOR_NAME: actions
  GIT_AUTHOR_EMAIL: wjessen@thefarmersdog.com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: jetli/trunk-action@v0.4.0
      - run: rustup target add wasm32-unknown-unknown
      - run: trunk build --public-url rust-client --release -d docs
      - run: git add -f docs/
      - uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: master
